apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-with-https
spec:
  selector:
    matchLabels:
      app: ingress-with-https
  template:
    metadata:
      labels:
        app: ingress-with-https
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-with-https
spec:
  selector:
    app: ingress-with-https
  ports:
  - port: 80
    targetPort: web
    name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-with-https
  labels:
    name: ingress-with-https
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  rules:
  - host: index.autumnin.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: ingress-with-https
          servicePort: web
  tls:
    - hosts:
        - index.autumnin.com
      secretName: index-tls

