apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
type: Opaque
data:
  access-key: TFRBSTV0OENSaDhIQ3pMOHRvRzMzZ2JI
  secret-key: RTZNR0NDaFJpcm5xanJ6enpMazByUjZVOXpQdTZB