apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: autumnin-cert
  namespace: cert-manager
spec:
  issuerRef:
    name: autumnin-dns01
    kind: ClusterIssuer
  secretName: alidns-secret
  commonName: "*.autumnin.com"
  dnsNames:
    - "autumnin.com"
    - "*.autumnin.com"