apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-test
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  labels:
    name: nginx-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 认证类型
    nginx.ingress.kubernetes.io/auth-type: basic
    # 包含 user/password 定义的 secret 对象名
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # 要显示的带有适当上下文的消息，说明需要身份验证的原因
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  rules:
  - host: autumnin.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: nginx-test
          servicePort: 80
---
apiVersion: v1
data:
  README.md: IyBBZGQgYXV0aG9yYXRpb24gZm9yIGluZ3Jlc3MKIyMgQ3JlYXRlIGEgYXV0aCBjZXJ0IHdpdGggc2VjcmV0Ci0gaHRwYXNzd2QgLWMgYXV0aCBmb28KICAKLSBrdWJlY3RsIGNyZWF0ZSBzZWNyZXQgZ2VuZXJpYyBiYXNpYy1hdXRoIC0tZnJvbSBhdXRoCiMjIEFkZCBpbmdyZXNzIGF1dGggCnVwZGF0ZSBuZ2lueC10ZXN0IGFubm90YXRpb25zIApuZ2lueC5pbmdyZXNzLmt1YmVybmV0ZXMuaW8vYXV0aC10eXBlOiBiYXNpYwpuZ2lueC5pbmdyZXNzLmt1YmVybmV0ZXMuaW8vYXV0aC1zZWNyZXQ6IGJhc2ljLWF1dGgKbmdpbnguaW5ncmVzcy5rdWJlcm5ldGVzLmlvL2F1dGgtcmVhbG06ICdBdXRoZW50aWNhdGlvbiBSZXF1aXJlZCAtIGZvbyc=
  auth: Zm9vOiRhcHIxJFgvaTZhZC8yJHd4Rmd5MU9zalVWdzgveEZLR2tmdjAK
kind: Secret
metadata:
  creationTimestamp: "2022-09-04T06:20:59Z"
  name: basic-auth
  namespace: default
type: Opaque