apiVersion: v1
kind: Pod
metadata:
  name: secret-volume
spec:
  volumes:
    - name: secret-info
      secret:
        secretName: mysecret
  restartPolicy: Never
  containers:
  - name: secret-volume
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "ls  /tmp/secects"
    volumeMounts:
      - mountPath: /tmp/secects
        name: secret-info
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  
