apiVersion: v1
kind: Pod
metadata:
  name: serect-env
  labels:
    name: serect
spec:
  containers:
  - name: serect-env
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "env |grep SERECT"
    env:
      - name: SERECT_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: mysecret
      - name: SERECT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password 
            name: mysecret
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
        