# 将secert的value挂载到指定的文件上
apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-item
spec:
  volumes:
    - name: secret-info
      secret:
        secretName: mysecret
        items:
          - key: username
            path: info/username
          - key: password
            path: info/password
  containers:
  - name: secret-volume-item
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "cat /tmp/secects/info/password"
    volumeMounts:
      - mountPath: /tmp/secects
        name: secret-info
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
