apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-domain
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dns-domain
  template:
    metadata:
      labels:
        app: dns-domain
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: dns-domain
spec:
  selector:
    app: dns-domain
  ports:
  - port: 5000
    targetPort: nginx
