apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  labels:
    name: dns-test
spec:
  containers:
  - name: test
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "env"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"