apiVersion: v1
kind: Pod
metadata:
  name: openebs-hostpath
  labels:
    name: openebs
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-openebs
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - 'while true; do echo "`date` [`hostname`] Hello from OpenEBS Local PV." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
