apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openebs
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
