apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-nginx
spec:
  selector:
    matchLabels:
      app: nodeport
  template:
    metadata:
      labels:
        app: nodeport
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-nginx
spec:
  selector:
    app: nodeport
  type: NodePort
  ports:
  - port: 80
    targetPort: web

