apiVersion: v1
kind: Pod
metadata:
  name: cpd-demo
  labels:
    name: cpd
spec:
  containers:
  - name: cpd
    image: busybox
    command:
      - "sh"
      - "-c"
      - "sleep 60m"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      capabilities:
        add:
          - "NET_ADMIN"
        drop:
          - "KILL"
