apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: autumnin-wordpress
spec:
  replicas: 2
  strategy: # 滚动更新策略
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        type: RollingUpdate
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      affinity: #避免单点故障
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - wordpress
      containers:
      - name: wordpress
        image: wordpress:5.3.2-apache
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name:  wdport
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql:3306
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_PASSWORD
        lifecycle:
          preStop: # 生命周期钩子，留了时间给 Endpoints 控制器和 kube-proxy 更新去 Endpoints 对象和转发规则 当Pod被销毁处于terminating,还是可以处理请求，因为sleep 20s 并没有被真正的销毁
            exec:
              command: ["/bin/bash","-c","sleep 20"]
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: autumnin-wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: wdport
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  labels:
    name: autumnin-wordpress
spec:
  rules:
  - host: autumnin.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <Service>
            port: 
              number: <Port>
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: autumnin-wordpress
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz
