apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" . }}
data:
  myvalue: "Hello World"
  {{- $chartName := .Release.Name -}}
  # {{- with .Values.favorite }}
  # drank: {{ .drank | default "tea" | quote | upper }}
  # sport: {{ .sport | quote }}
  # release: {{ $chartName }}
  # {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | quote | title }}
    {{- end }}
  sizes: |-
    {{- range tuple "small" "medium" "lange" }}
    - {{ . }}
    {{- end }}
  kinds: |-
    {{- range $index,$item := .Values.pizzaToppings }}
    {{ $index }}: {{ $item }}
    {{- end }}
  {{- range $key,$item := .Values.favorite }}
  {{ $key }}: {{ $item }}
  {{- end }}
{{ include "mychart.app" . | indent 2 }}
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $files.Get . }}
  {{- end }}