apiVersion: v1
kind: Namespace
metadata:
  name: kube-example
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: kube-example
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
  - port: 3306
    targetPort: dbport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wordpress-mysql
  namespace: kube-example
  labels:
    app:  wordpress
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app:  wordpress
        tier: mysql
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mysql
        image:  mysql:5.7
        args:  # 新版本镜像有更新，需要使用下面的认证插件环境变量配置才会生效
        - --default_authentication_plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootPassW0rd
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name:  MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306
          name:  dbport
        