apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: wordpress
  namespace: kube-example
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend 
  