apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox:latest
    args:
      - "/bin/sh"
      - "-c"
      - "touch /tmp/healthy;sleep 30;rm -rf /tmp/healthy;sleep 600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
