apiVersion: v1
kind: Pod
metadata:
  name: hook-demo2
spec:
  containers:
  - name: hook-demo2
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    lifecycle:
      preStop:
        exec:
          command:
            - "/usr/sbin/nginx"
            - "-s"
            - "quit"

---
apiVersion: v1
kind: Pod
metadata:
  name: hook-demo3
spec:
  volumes:
  - name: message
    hostPath:
     path: /tmp
  containers:
  - name: hook-demo3
    image: nginx:1.7.9
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: message
      mountPath: /usr/share
    lifecycle:
      preStop:
        exec:
          command:
          - "/bin/sh"
          - "-c"
          - "echo Hello from preStop handle > /usr/share/message"
