apiVersion: v1
kind: Pod
metadata:
  name: hook-dem1
spec:
  containers:
  - name: hook-demo1
    image: nginx:1.7.9
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    lifecycle:
      postStart:
        exec:
          command:
          - "/bin/sh"
          - "-c" 
          - "echo Hello from postStart handler> /usr/share/message"

