apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    name: static
spec:
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
