apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    name: volume-pod
  annotations:
    own: guoyang
    build: test
spec:
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
  containers:
  - name: volume-pod
    image: busybox:latest
    command:
      - "sleep"
      - "3000"
    volumeMounts:
      - mountPath: /etc/podinfo
        name: podinfo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

