
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autumnin
  
spec:
  selector:
    matchLabels:
      app: autumnin
  template:
    metadata:
      labels:
        app: autumnin
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: autumnin
  
spec:
  selector:
    app: autumnin
  ports:
  - port: 80
    targetPort: 80
    name: http
---    
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: autumnin
  
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-http01"  # 使用哪个issuer 
spec:
  tls:
  - hosts:
    - autumnin.com    # TLS 域名
    secretName: autumnin-tls   # 用于存储证书的 Secret 对象名字 
  rules:
  - host: autumnin.com
    http:
      paths:
      - path: /
        backend:
          serviceName: autumnin
          servicePort: 80